load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "strings",
    srcs = ["string.go"],
    importpath = "github.com/gnolang/gno/tm2/pkg/strings",
    visibility = ["//visibility:public"],
)

alias(
    name = "go_default_library",
    actual = ":strings",
    visibility = ["//visibility:public"],
)
