load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "pkg",
    srcs = [
        "pkg.go",
        "pkgset.go",
    ],
    importpath = "github.com/gnolang/gno/tm2/pkg/amino/pkg",
    visibility = ["//visibility:public"],
)

alias(
    name = "go_default_library",
    actual = ":pkg",
    visibility = ["//visibility:public"],
)
