load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "params",
    srcs = ["params.go"],
    importpath = "github.com/gnolang/gno/gnovm/stdlibs/sys/params",
    visibility = ["//visibility:public"],
    deps = [
        "//gnovm/pkg/gnolang",
        "//gnovm/stdlibs/std",
    ],
)

alias(
    name = "go_default_library",
    actual = ":params",
    visibility = ["//visibility:public"],
)
