load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "logname_lib",
    srcs = [
        "colors.go",
        "main.go",
    ],
    importpath = "github.com/gnolang/gno/gno.land/pkg/gnoweb/tools/cmd/logname",
    visibility = ["//visibility:private"],
    deps = ["@com_github_charmbracelet_lipgloss//:go_default_library"],
)

go_binary(
    name = "logname",
    embed = [":logname_lib"],
    visibility = ["//visibility:public"],
)
