load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "std",
    srcs = ["std.go"],
    importpath = "github.com/gnolang/gno/gnovm/tests/stdlibs/std",
    visibility = ["//visibility:public"],
    deps = [
        "//gnovm/pkg/gnolang",
        "//gnovm/stdlibs/std",
        "//tm2/pkg/crypto",
        "//tm2/pkg/std",
    ],
)

alias(
    name = "go_default_library",
    actual = ":std",
    visibility = ["//visibility:public"],
)
