load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "aminoscan_lib",
    srcs = [
        "aminoscan.go",
        "colors.go",
    ],
    importpath = "github.com/gnolang/gno/tm2/pkg/amino/cmd/aminoscan",
    visibility = ["//visibility:private"],
    deps = ["//tm2/pkg/amino"],
)

go_binary(
    name = "aminoscan",
    embed = [":aminoscan_lib"],
    visibility = ["//visibility:public"],
)
