load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "indexparser_lib",
    srcs = ["main.go"],
    importpath = "github.com/gnolang/gno/misc/docs/tools/indexparser",
    visibility = ["//visibility:private"],
    deps = [
        "@com_github_peterbourgon_ff_v3//:ff",
        "@com_github_yuin_goldmark//:goldmark",
        "@com_github_yuin_goldmark//ast",
        "@com_github_yuin_goldmark//text",
    ],
)

go_binary(
    name = "indexparser",
    embed = [":indexparser_lib"],
    visibility = ["//visibility:public"],
)
