load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "config",
    srcs = [
        "config.go",
        "utils.go",
    ],
    importpath = "github.com/gnolang/gno/tm2/pkg/bft/mempool/config",
    visibility = ["//visibility:public"],
    deps = ["//tm2/pkg/errors"],
)

alias(
    name = "go_default_library",
    actual = ":config",
    visibility = ["//visibility:public"],
)
