load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "matrix",
    srcs = [
        "cmd.go",
        "matrix.go",
    ],
    importpath = "github.com/gnolang/gno/contribs/github-bot/internal/matrix",
    visibility = ["//contribs/github-bot:__subpackages__"],
    deps = [
        "//contribs/github-bot/internal/client",
        "//contribs/github-bot/internal/utils",
        "//tm2/pkg/commands",
        "@com_github_sethvargo_go_githubactions//:go_default_library",
    ],
)

alias(
    name = "go_default_library",
    actual = ":matrix",
    visibility = ["//contribs/github-bot:__subpackages__"],
)
