load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "autofile",
    srcs = [
        "autofile.go",
        "autofile_unix.go",
        "autofile_wasm.go",
        "group.go",
    ],
    importpath = "github.com/gnolang/gno/tm2/pkg/autofile",
    visibility = ["//visibility:public"],
    deps = [
        "//tm2/pkg/random",
        "//tm2/pkg/service",
    ],
)

alias(
    name = "go_default_library",
    actual = ":autofile",
    visibility = ["//visibility:public"],
)
