#!/bin/bash
# Setup script for Bazel - creates necessary symlinks

set -euo pipefail

# Get the repository root
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
BAZEL_DIR="${REPO_ROOT}/misc/bazel"

# Create symlinks in repo root
cd "$REPO_ROOT"

# Create symlinks to bazel files
ln -sf misc/bazel/WORKSPACE WORKSPACE
ln -sf misc/bazel/BUILD.bazel BUILD.bazel
ln -sf misc/bazel/.bazelrc .bazelrc
ln -sf misc/bazel/.bazelignore .bazelignore
ln -sf misc/bazel/.bazelversion .bazelversion

# Create deps.bzl placeholder if it doesn't exist
if [ ! -f "${BAZEL_DIR}/deps.bzl" ]; then
    cat > "${BAZEL_DIR}/deps.bzl" << 'EOF'
"""Go dependencies for Bazel. Generated by gazelle."""

def go_dependencies():
    """Load Go dependencies. This will be populated by gazelle."""
    pass
EOF
fi

# Create symlink for deps.bzl
ln -sf misc/bazel/deps.bzl deps.bzl

# Create symlinks for rule files only if they exist
for rule in gno_deps.bzl rules/gno_test.bzl rules/filetest.bzl rules/txtar_test.bzl; do
    if [ -f "${BAZEL_DIR}/${rule}" ]; then
        ln -sf "misc/bazel/${rule}" "$(basename "${rule}")"
    fi
done