load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "gnokey_lib",
    srcs = ["main.go"],
    importpath = "github.com/gnolang/gno/gno.land/cmd/gnokey",
    visibility = ["//visibility:private"],
    deps = [
        "//gno.land/pkg/keyscli",
        "//gnovm/pkg/gnoenv",
        "//tm2/pkg/commands",
        "//tm2/pkg/crypto/keys/client",
    ],
)

go_binary(
    name = "gnokey",
    embed = [":gnokey_lib"],
    visibility = ["//visibility:public"],
)
