load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "gnomigrate_lib",
    srcs = [
        "main.go",
        "migrate.go",
    ],
    importpath = "github.com/gnolang/gno/contribs/gnomigrate",
    visibility = ["//visibility:private"],
    deps = ["//tm2/pkg/commands"],
)

go_binary(
    name = "gnomigrate",
    embed = [":gnomigrate_lib"],
    visibility = ["//visibility:public"],
)
