load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "gnoweb",
    srcs = [
        "app.go",
        "cache.go",
        "client.go",
        "client_mock.go",
        "handler_http.go",
        "redirect.go",
        "render.go",
        "render_config.go",
        "render_lexer.go",
        "static.go",
        "status.go",
    ],
    embedsrcs = [
        "public/favicon.ico",
        "public/fonts/intervar/Intervar.woff2",
        "public/fonts/roboto/roboto-mono-normal.woff",
        "public/fonts/roboto/roboto-mono-normal.woff2",
        "public/imgs/gnoland.svg",
        "public/js/breadcrumb.js",
        "public/js/copy.js",
        "public/js/index.js",
        "public/js/list.js",
        "public/js/realmhelp.js",
        "public/js/searchbar.js",
        "public/js/tooltip.js",
        "public/js/utils.js",
        "public/styles.css",
    ],
    importpath = "github.com/gnolang/gno/gno.land/pkg/gnoweb",
    visibility = ["//visibility:public"],
    deps = [
        "//gno.land/pkg/gnoweb/components",
        "//gno.land/pkg/gnoweb/markdown",
        "//gno.land/pkg/gnoweb/weburl",
        "//gno.land/pkg/sdk/vm",
        "//gnovm/pkg/doc",
        "//tm2/pkg/amino",
        "//tm2/pkg/bech32",
        "//tm2/pkg/bft/abci/types",
        "//tm2/pkg/bft/rpc/client",
        "//tm2/pkg/errors",
        "@com_github_alecthomas_chroma_v2//:chroma",
        "@com_github_alecthomas_chroma_v2//formatters/html",
        "@com_github_alecthomas_chroma_v2//lexers",
        "@com_github_alecthomas_chroma_v2//styles",
        "@com_github_yuin_goldmark//:goldmark",
        "@com_github_yuin_goldmark//extension",
        "@com_github_yuin_goldmark//parser",
        "@com_github_yuin_goldmark//renderer/html",
        "@com_github_yuin_goldmark//text",
        "@com_github_yuin_goldmark_highlighting_v2//:goldmark-highlighting",
    ],
)

alias(
    name = "go_default_library",
    actual = ":gnoweb",
    visibility = ["//visibility:public"],
)
