load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "integration",
    srcs = [
        "doc.go",
        "node_testing.go",
        "pkgloader.go",
        "process.go",
        "testscript_gnoland.go",
        "testscript_testing.go",
        "utils.go",
    ],
    importpath = "github.com/gnolang/gno/gno.land/pkg/integration",
    visibility = ["//visibility:public"],
    deps = [
        "//gno.land/pkg/gnoland",
        "//gno.land/pkg/gnoland/ugnot",
        "//gno.land/pkg/keyscli",
        "//gno.land/pkg/sdk/vm",
        "//gnovm/pkg/gnoenv",
        "//gnovm/pkg/gnolang",
        "//gnovm/pkg/gnomod",
        "//gnovm/pkg/packages",
        "//tm2/pkg/amino",
        "//tm2/pkg/bft/abci/types",
        "//tm2/pkg/bft/config",
        "//tm2/pkg/bft/node",
        "//tm2/pkg/bft/rpc/client",
        "//tm2/pkg/bft/rpc/core/types",
        "//tm2/pkg/bft/types",
        "//tm2/pkg/commands",
        "//tm2/pkg/crypto",
        "//tm2/pkg/crypto/bip39",
        "//tm2/pkg/crypto/ed25519",
        "//tm2/pkg/crypto/hd",
        "//tm2/pkg/crypto/keys",
        "//tm2/pkg/crypto/keys/client",
        "//tm2/pkg/crypto/secp256k1",
        "//tm2/pkg/db",
        "//tm2/pkg/db/goleveldb",
        "//tm2/pkg/db/memdb",
        "//tm2/pkg/sdk/auth",
        "//tm2/pkg/sdk/bank",
        "//tm2/pkg/std",
        "@com_github_rogpeppe_go_internal//testscript",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)

alias(
    name = "go_default_library",
    actual = ":integration",
    visibility = ["//visibility:public"],
)
