load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "ledger",
    srcs = ["ledger_secp256k1.go"],
    importpath = "github.com/gnolang/gno/tm2/pkg/crypto/ledger",
    visibility = ["//visibility:public"],
    deps = [
        "//tm2/pkg/amino",
        "//tm2/pkg/crypto",
        "//tm2/pkg/crypto/hd",
        "//tm2/pkg/crypto/internal/ledger",
        "//tm2/pkg/crypto/secp256k1",
        "//tm2/pkg/errors",
        "@com_github_btcsuite_btcd_btcec_v2//:btcec",
        "@com_github_btcsuite_btcd_btcec_v2//ecdsa",
        "@com_github_decred_dcrd_dcrec_secp256k1_v4//:secp256k1",
    ],
)

alias(
    name = "go_default_library",
    actual = ":ledger",
    visibility = ["//visibility:public"],
)
