load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "gno_lib",
    srcs = [
        "bug.go",
        "clean.go",
        "common.go",
        "doc.go",
        "download_deps.go",
        "env.go",
        "fmt.go",
        "lint.go",
        "main.go",
        "mod.go",
        "repl.go",
        "run.go",
        "test.go",
        "testutil.go",
        "tool.go",
        "tool_fix.go",
        "tool_transpile.go",
        "util.go",
        "version.go",
    ],
    importpath = "github.com/gnolang/gno/gnovm/cmd/gno",
    visibility = ["//visibility:private"],
    deps = [
        "//gnovm/cmd/gno/internal/pkgdownload",
        "//gnovm/cmd/gno/internal/pkgdownload/rpcpkgfetcher",
        "//gnovm/pkg/doc",
        "//gnovm/pkg/gnoenv",
        "//gnovm/pkg/gnofmt",
        "//gnovm/pkg/gnolang",
        "//gnovm/pkg/gnomod",
        "//gnovm/pkg/packages",
        "//gnovm/pkg/repl",
        "//gnovm/pkg/test",
        "//gnovm/pkg/transpiler",
        "//gnovm/pkg/version",
        "//tm2/pkg/colors",
        "//tm2/pkg/commands",
        "//tm2/pkg/errors",
        "//tm2/pkg/std",
        "//tm2/pkg/store/types",
        "@com_github_bendory_conway_hebrew_calendar//:conway-hebrew-calendar",
        "@com_github_rogpeppe_go_internal//diff",
        "@org_golang_x_mod//module",
        "@org_uber_go_multierr//:multierr",
    ],
)

go_binary(
    name = "gno",
    embed = [":gno_lib"],
    visibility = ["//visibility:public"],
)
