load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "batch",
    srcs = ["batch.go"],
    importpath = "github.com/gnolang/gno/tm2/pkg/bft/rpc/lib/client/batch",
    visibility = ["//visibility:public"],
    deps = ["//tm2/pkg/bft/rpc/lib/types"],
)

alias(
    name = "go_default_library",
    actual = ":batch",
    visibility = ["//visibility:public"],
)
