load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "gnoland",
    srcs = [
        "app.go",
        "balance.go",
        "events.go",
        "genesis.go",
        "node_inmemory.go",
        "package.go",
        "test_common.go",
        "types.go",
        "validators.go",
    ],
    importpath = "github.com/gnolang/gno/gno.land/pkg/gnoland",
    visibility = ["//visibility:public"],
    deps = [
        "//gno.land/pkg/sdk/vm",
        "//gnovm/pkg/gnoenv",
        "//gnovm/pkg/gnolang",
        "//gnovm/stdlibs/std",
        "//tm2/pkg/amino",
        "//tm2/pkg/bft/abci/types",
        "//tm2/pkg/bft/config",
        "//tm2/pkg/bft/node",
        "//tm2/pkg/bft/proxy",
        "//tm2/pkg/bft/types",
        "//tm2/pkg/crypto",
        "//tm2/pkg/crypto/ed25519",
        "//tm2/pkg/db",
        "//tm2/pkg/db/_tags",
        "//tm2/pkg/db/goleveldb",
        "//tm2/pkg/db/memdb",
        "//tm2/pkg/events",
        "//tm2/pkg/log",
        "//tm2/pkg/os",
        "//tm2/pkg/p2p/types",
        "//tm2/pkg/sdk",
        "//tm2/pkg/sdk/auth",
        "//tm2/pkg/sdk/bank",
        "//tm2/pkg/sdk/config",
        "//tm2/pkg/sdk/params",
        "//tm2/pkg/std",
        "//tm2/pkg/store",
        "//tm2/pkg/store/dbadapter",
        "//tm2/pkg/store/iavl",
        "//tm2/pkg/store/types",
        "@com_github_pelletier_go_toml//:go-toml",
        "@com_github_rs_xid//:xid",
    ],
)

alias(
    name = "go_default_library",
    actual = ":gnoland",
    visibility = ["//visibility:public"],
)
