load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "pkgdownload",
    srcs = [
        "pkgdownload.go",
        "pkgfetcher.go",
    ],
    importpath = "github.com/gnolang/gno/gnovm/cmd/gno/internal/pkgdownload",
    visibility = ["//gnovm/cmd/gno:__subpackages__"],
    deps = ["//tm2/pkg/std"],
)

alias(
    name = "go_default_library",
    actual = ":pkgdownload",
    visibility = ["//gnovm/cmd/gno:__subpackages__"],
)
