load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "detrand",
    srcs = ["detrand.go"],
    importpath = "github.com/gnolang/gno/tm2/pkg/amino/libs/detrand",
    visibility = ["//visibility:public"],
)

alias(
    name = "go_default_library",
    actual = ":detrand",
    visibility = ["//visibility:public"],
)
