load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "init-corpus_lib",
    srcs = ["main.go"],
    importpath = "github.com/gnolang/gno/tm2/pkg/amino/tests/fuzz/binary/init-corpus",
    visibility = ["//visibility:private"],
    deps = [
        "//tm2/pkg/amino",
        "//tm2/pkg/amino/tests",
    ],
)

go_binary(
    name = "init-corpus",
    embed = [":init-corpus_lib"],
    visibility = ["//visibility:public"],
)
