load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "debug_lib",
    srcs = ["main.go"],
    importpath = "github.com/gnolang/gno/tm2/pkg/amino/tests/fuzz/json/debug",
    visibility = ["//visibility:private"],
    deps = [
        "//tm2/pkg/amino",
        "//tm2/pkg/amino/tests",
    ],
)

go_binary(
    name = "debug",
    embed = [":debug_lib"],
    visibility = ["//visibility:public"],
)
