load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "mock",
    srcs = ["mock.go"],
    importpath = "github.com/gnolang/gno/tm2/pkg/bft/mempool/mock",
    visibility = ["//visibility:public"],
    deps = [
        "//tm2/pkg/bft/abci/types",
        "//tm2/pkg/bft/mempool",
        "//tm2/pkg/bft/types",
        "//tm2/pkg/clist",
    ],
)

alias(
    name = "go_default_library",
    actual = ":mock",
    visibility = ["//visibility:public"],
)
