load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "ugnot",
    srcs = ["denom.go"],
    importpath = "github.com/gnolang/gno/gno.land/pkg/gnoland/ugnot",
    visibility = ["//visibility:public"],
)

alias(
    name = "go_default_library",
    actual = ":ugnot",
    visibility = ["//visibility:public"],
)
