load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "versionset",
    srcs = ["versionset.go"],
    importpath = "github.com/gnolang/gno/tm2/pkg/versionset",
    visibility = ["//visibility:public"],
    deps = ["@org_golang_x_mod//semver"],
)

alias(
    name = "go_default_library",
    actual = ":versionset",
    visibility = ["//visibility:public"],
)
