load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "cfg",
    srcs = ["cfg.go"],
    importpath = "github.com/gnolang/gno/misc/loop/cmd/cfg",
    visibility = ["//visibility:public"],
)

alias(
    name = "go_default_library",
    actual = ":cfg",
    visibility = ["//visibility:public"],
)
