load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "mock",
    srcs = [
        "mock.go",
        "package.go",
    ],
    importpath = "github.com/gnolang/gno/tm2/pkg/crypto/mock",
    visibility = ["//visibility:public"],
    deps = [
        "//tm2/pkg/amino",
        "//tm2/pkg/crypto",
        "//tm2/pkg/random",
    ],
)

alias(
    name = "go_default_library",
    actual = ":mock",
    visibility = ["//visibility:public"],
)
