load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "time",
    srcs = ["time.go"],
    importpath = "github.com/gnolang/gno/tm2/pkg/bft/types/time",
    visibility = ["//visibility:public"],
)

alias(
    name = "go_default_library",
    actual = ":time",
    visibility = ["//visibility:public"],
)
