load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "testutils",
    srcs = [
        "flappy.go",
        "io.go",
        "mutate.go",
        "os.go",
    ],
    importpath = "github.com/gnolang/gno/tm2/pkg/testutils",
    visibility = ["//visibility:public"],
    deps = ["//tm2/pkg/random"],
)

alias(
    name = "go_default_library",
    actual = ":testutils",
    visibility = ["//visibility:public"],
)
