load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "sha256",
    srcs = ["sha256.go"],
    importpath = "github.com/gnolang/gno/gnovm/stdlibs/crypto/sha256",
    visibility = ["//visibility:public"],
)

alias(
    name = "go_default_library",
    actual = ":sha256",
    visibility = ["//visibility:public"],
)
