load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "timer",
    srcs = ["throttle_timer.go"],
    importpath = "github.com/gnolang/gno/tm2/pkg/timer",
    visibility = ["//visibility:public"],
)

alias(
    name = "go_default_library",
    actual = ":timer",
    visibility = ["//visibility:public"],
)
