load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "metrics",
    srcs = ["metrics.go"],
    importpath = "github.com/gnolang/gno/tm2/pkg/telemetry/metrics",
    visibility = ["//visibility:public"],
    deps = [
        "//tm2/pkg/telemetry/config",
        "@io_opentelemetry_go_otel//:otel",
        "@io_opentelemetry_go_otel//semconv/v1.4.0:v1_4_0",
        "@io_opentelemetry_go_otel_exporters_otlp_otlpmetric_otlpmetricgrpc//:otlpmetricgrpc",
        "@io_opentelemetry_go_otel_exporters_otlp_otlpmetric_otlpmetrichttp//:otlpmetrichttp",
        "@io_opentelemetry_go_otel_metric//:metric",
        "@io_opentelemetry_go_otel_sdk//resource",
        "@io_opentelemetry_go_otel_sdk_metric//:metric",
    ],
)

alias(
    name = "go_default_library",
    actual = ":metrics",
    visibility = ["//visibility:public"],
)
