load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "client",
    srcs = [
        "add.go",
        "add_bech32.go",
        "add_ledger.go",
        "add_multisig.go",
        "broadcast.go",
        "common.go",
        "delete.go",
        "export.go",
        "generate.go",
        "helper.go",
        "import.go",
        "list.go",
        "maketx.go",
        "multisign.go",
        "query.go",
        "root.go",
        "rotate.go",
        "send.go",
        "sign.go",
        "verify.go",
    ],
    importpath = "github.com/gnolang/gno/tm2/pkg/crypto/keys/client",
    visibility = ["//visibility:public"],
    deps = [
        "//tm2/pkg/amino",
        "//tm2/pkg/bft/abci/types",
        "//tm2/pkg/bft/rpc/client",
        "//tm2/pkg/bft/rpc/core/types",
        "//tm2/pkg/commands",
        "//tm2/pkg/crypto",
        "//tm2/pkg/crypto/bip39",
        "//tm2/pkg/crypto/hd",
        "//tm2/pkg/crypto/keys",
        "//tm2/pkg/crypto/keys/armor",
        "//tm2/pkg/crypto/multisig",
        "//tm2/pkg/crypto/secp256k1",
        "//tm2/pkg/errors",
        "//tm2/pkg/overflow",
        "//tm2/pkg/sdk/bank",
        "//tm2/pkg/std",
        "@com_github_peterbourgon_ff_v3//:ff",
        "@com_github_peterbourgon_ff_v3//fftoml",
    ],
)

alias(
    name = "go_default_library",
    actual = ":client",
    visibility = ["//visibility:public"],
)
