load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "components",
    srcs = [
        "component.go",
        "layout_footer.go",
        "layout_header.go",
        "layout_index.go",
        "template.go",
        "ui_breadcrumb.go",
        "view.go",
        "view_directory.go",
        "view_help.go",
        "view_realm.go",
        "view_redirect.go",
        "view_source.go",
        "view_status.go",
        "view_user.go",
    ],
    embedsrcs = [
        "layouts/analytics.html",
        "layouts/article.html",
        "layouts/aside.html",
        "layouts/footer.html",
        "layouts/head.html",
        "layouts/header.html",
        "layouts/index.html",
        "ui/breadcrumb.html",
        "ui/btn_copy.html",
        "ui/code_wrapper.html",
        "ui/expend_label.html",
        "ui/header_link.html",
        "ui/help_function.html",
        "ui/icons.html",
        "ui/logo.html",
        "ui/toc_generic.html",
        "ui/toc_realm.html",
        "ui/toc_source.html",
        "views/directory.html",
        "views/help.html",
        "views/realm.html",
        "views/redirect.html",
        "views/source.html",
        "views/status.html",
        "views/user.html",
    ],
    importpath = "github.com/gnolang/gno/gno.land/pkg/gnoweb/components",
    visibility = ["//visibility:public"],
    deps = [
        "//gno.land/pkg/gnoweb/markdown",
        "//gno.land/pkg/gnoweb/weburl",
        "//gnovm/pkg/doc",
    ],
)

alias(
    name = "go_default_library",
    actual = ":components",
    visibility = ["//visibility:public"],
)
