load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "noop",
    srcs = ["noop.go"],
    importpath = "github.com/gnolang/gno/contribs/tx-archive/log/noop",
    visibility = ["//visibility:public"],
)

alias(
    name = "go_default_library",
    actual = ":noop",
    visibility = ["//visibility:public"],
)
